version: '2.1'

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    environment:
      DOCKER_BUILDKIT: '1'
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: docker build -t influxdb .

workflows:
  version: 2
  build:
    jobs:
      - build
